### ISSUE TITLE
Can't send mail

### ISSUE THREAD

**Issue by felixhammerl** [whiteout-io/mail-html5#178]
for unknown reasons, it seems to be possible to send a mail with no recipients

    [DEBUG][2014-11-10T23:55:23.221Z][SMTP Client] SERVER: 220 ESMTP [server]

    [DEBUG][2014-11-10T23:55:23.221Z][SMTP Client] Sending EHLO ip-172-31-18-41
    [DEBUG][2014-11-10T23:55:23.439Z][SMTP Client] SERVER: 250-[server]
    250-PIPELINING
    250-SIZE 157286400
    250-AUTH PLAIN LOGIN
    250-AUTH=PLAIN LOGIN
    250-ENHANCEDSTATUSCODES
    250 8BITMIME

    [DEBUG][2014-11-10T23:55:23.440Z][SMTP Client] Server supports AUTH PLAIN
    [DEBUG][2014-11-10T23:55:23.440Z][SMTP Client] Server supports AUTH LOGIN
    [DEBUG][2014-11-10T23:55:23.440Z][SMTP Client] Maximum allowd message size: 157286400
    [DEBUG][2014-11-10T23:55:23.440Z][SMTP Client] Authentication via AUTH PLAIN
    [DEBUG][2014-11-10T23:55:23.652Z][SMTP Client] SERVER: 235 2.7.0 Authentication successful

    [DEBUG][2014-11-10T23:55:23.652Z][SMTP Client] Authentication successful.
    [DEBUG][2014-11-10T23:55:23.652Z][SMTP Client] Sending MAIL FROM...
    [DEBUG][2014-11-10T23:55:23.856Z][SMTP Client] SERVER: 250 2.1.0 Ok

    [ERROR][2014-11-10T23:55:23.856Z][SMTP Client] Error: Can't send mail - no recipients defined . Stack: Error: Can't send mail - no recipients defined
    at SmtpClient._actionMAIL (https://mail.whiteout.io/js/app.min.js:18:15619)
    at SmtpClient._onCommand (https://mail.whiteout.io/js/app.min.js:18:9330)
    at SmtpResponseParser._processLine (https://mail.whiteout.io/js/app.min.js:18:3330)
    at SmtpResponseParser.send (https://mail.whiteout.io/js/app.min.js:18:2330)
    at SmtpClient._onData (https://mail.whiteout.io/js/app.min.js:18:8634)
    at TCPSocket._emit (https://mail.whiteout.io/js/app.min.js:18:1109)
    at TCPSocket.tlsinbound (https://mail.whiteout.io/js/app.min.js:17:31278)
    at Worker.self._tlsWorker.onmessage (https://mail.whiteout.io/js/app.min.js:18:468)

**Comment by tanx** [comment]
This should be fixed. The send button is disabled for no recipients.
